# Generated by Django 3.0.8 on 2020-08-06 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagebazar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='Images',
            new_name='Image',
        ),
    ]
